const mongoose = require('mongoose');
const Recipe = require('./models/Recipe');

const recipes = [
  {
    name: 'Spaghetti Carbonara',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Spaghetti', 'Eggs', 'Parmesan Cheese', 'Pancetta', 'Black Pepper', 'Salt'],
    steps: ['Boil pasta', 'Cook pancetta', 'Mix eggs and cheese', 'Combine all and season'],
    nutrition: { calories: 400, protein: 18, fat: 15, carbs: 55 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: ['Gluten'],
    substitutions: ['Turkey bacon for pancetta'],
  },
  {
    name: 'Chicken Tikka Masala',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Chicken', 'Yogurt', 'Tomato Puree', 'Onion', 'Garlic', 'Garam Masala', 'Cream'],
    steps: ['Marinate chicken', 'Cook onion and spices', 'Add tomato and cream', 'Simmer chicken'],
    nutrition: { calories: 520, protein: 32, fat: 28, carbs: 38 },
    difficulty: 'Medium',
    cookingTime: 40,
    dietaryRestrictions: [],
    substitutions: ['Paneer for chicken'],
  },
  {
    name: 'Vegetable Stir Fry',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Broccoli', 'Carrots', 'Bell Pepper', 'Soy Sauce', 'Garlic', 'Ginger', 'Sesame Oil'],
    steps: ['Chop vegetables', 'Stir fry in oil', 'Add sauce and cook'],
    nutrition: { calories: 220, protein: 6, fat: 8, carbs: 32 },
    difficulty: 'Easy',
    cookingTime: 20,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Tamari for soy sauce'],
  },
  {
    name: 'Beef Tacos',
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc',
    ingredients: ['Taco Shells', 'Ground Beef', 'Lettuce', 'Cheddar Cheese', 'Tomato', 'Sour Cream'],
    steps: ['Cook beef', 'Fill shells', 'Add toppings'],
    nutrition: { calories: 350, protein: 16, fat: 20, carbs: 28 },
    difficulty: 'Easy',
    cookingTime: 30,
    dietaryRestrictions: [],
    substitutions: ['Ground turkey for beef'],
  },
  {
    name: 'Greek Salad',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Cucumber', 'Tomato', 'Feta Cheese', 'Olives', 'Red Onion', 'Olive Oil', 'Oregano'],
    steps: ['Chop vegetables', 'Mix with cheese and olives', 'Dress with oil and oregano'],
    nutrition: { calories: 180, protein: 5, fat: 12, carbs: 12 },
    difficulty: 'Easy',
    cookingTime: 15,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese for feta'],
  },
  {
    name: 'Egg Fried Rice',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Rice', 'Eggs', 'Green Peas', 'Carrots', 'Soy Sauce', 'Green Onion'],
    steps: ['Cook rice', 'Scramble eggs', 'Stir fry all together'],
    nutrition: { calories: 320, protein: 10, fat: 8, carbs: 52 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: [],
    substitutions: ['Brown rice for white rice'],
  },
  {
    name: 'Margherita Pizza',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Pizza Dough', 'Tomato Sauce', 'Mozzarella', 'Basil', 'Olive Oil'],
    steps: ['Prepare dough', 'Add sauce and cheese', 'Bake and top with basil'],
    nutrition: { calories: 290, protein: 12, fat: 9, carbs: 38 },
    difficulty: 'Medium',
    cookingTime: 35,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese for mozzarella'],
  },
  {
    name: 'Lentil Soup',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Lentils', 'Carrots', 'Celery', 'Onion', 'Garlic', 'Vegetable Broth'],
    steps: ['Chop vegetables', 'Simmer with lentils and broth'],
    nutrition: { calories: 210, protein: 11, fat: 3, carbs: 36 },
    difficulty: 'Easy',
    cookingTime: 40,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Chicken broth for vegetable broth'],
  },
  {
    name: 'Butter Chicken',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Chicken', 'Butter', 'Tomato Puree', 'Cream', 'Spices'],
    steps: ['Cook chicken', 'Add sauce ingredients', 'Simmer and serve'],
    nutrition: { calories: 600, protein: 30, fat: 38, carbs: 32 },
    difficulty: 'Medium',
    cookingTime: 45,
    dietaryRestrictions: [],
    substitutions: ['Paneer for chicken'],
  },
  {
    name: 'Falafel Wrap',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Falafel', 'Pita Bread', 'Lettuce', 'Tomato', 'Tahini Sauce'],
    steps: ['Prepare falafel', 'Fill pita', 'Add veggies and sauce'],
    nutrition: { calories: 340, protein: 12, fat: 14, carbs: 44 },
    difficulty: 'Easy',
    cookingTime: 30,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Hummus for tahini'],
  },
  {
    name: 'Pancakes',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Flour', 'Eggs', 'Milk', 'Sugar', 'Baking Powder', 'Butter'],
    steps: ['Mix ingredients', 'Cook on griddle', 'Serve with syrup'],
    nutrition: { calories: 260, protein: 7, fat: 8, carbs: 40 },
    difficulty: 'Easy',
    cookingTime: 20,
    dietaryRestrictions: [],
    substitutions: ['Almond milk for milk'],
  },
  {
    name: 'Caesar Salad',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Romaine Lettuce', 'Croutons', 'Parmesan', 'Caesar Dressing'],
    steps: ['Chop lettuce', 'Add croutons and cheese', 'Dress and toss'],
    nutrition: { calories: 190, protein: 6, fat: 12, carbs: 14 },
    difficulty: 'Easy',
    cookingTime: 15,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan dressing'],
  },
  {
    name: 'Tomato Soup',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Tomatoes', 'Onion', 'Garlic', 'Vegetable Broth', 'Cream'],
    steps: ['Cook tomatoes and onion', 'Blend', 'Add broth and cream'],
    nutrition: { calories: 150, protein: 4, fat: 6, carbs: 22 },
    difficulty: 'Easy',
    cookingTime: 35,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Coconut cream for dairy cream'],
  },
  {
    name: 'Grilled Cheese Sandwich',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Bread', 'Cheddar Cheese', 'Butter'],
    steps: ['Butter bread', 'Add cheese', 'Grill until golden'],
    nutrition: { calories: 320, protein: 10, fat: 18, carbs: 28 },
    difficulty: 'Easy',
    cookingTime: 10,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese'],
  },
  {
    name: 'Veggie Burger',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Veggie Patty', 'Burger Bun', 'Lettuce', 'Tomato', 'Onion', 'Ketchup'],
    steps: ['Cook patty', 'Assemble burger'],
    nutrition: { calories: 350, protein: 12, fat: 10, carbs: 48 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Gluten-free bun'],
  },
  {
    name: 'Chicken Caesar Wrap',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Chicken Breast', 'Tortilla', 'Romaine Lettuce', 'Caesar Dressing', 'Parmesan'],
    steps: ['Cook chicken', 'Fill tortilla', 'Add lettuce and dressing'],
    nutrition: { calories: 410, protein: 28, fat: 16, carbs: 38 },
    difficulty: 'Medium',
    cookingTime: 30,
    dietaryRestrictions: [],
    substitutions: ['Vegan chicken'],
  },
  {
    name: 'Mushroom Risotto',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Arborio Rice', 'Mushrooms', 'Onion', 'Parmesan', 'Vegetable Broth'],
    steps: ['Cook onion and mushrooms', 'Add rice and broth', 'Stir and add cheese'],
    nutrition: { calories: 330, protein: 8, fat: 10, carbs: 52 },
    difficulty: 'Medium',
    cookingTime: 45,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese'],
  },
  {
    name: 'Fish Tacos',
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc',
    ingredients: ['Taco Shells', 'White Fish', 'Cabbage', 'Lime', 'Sour Cream', 'Cilantro'],
    steps: ['Cook fish', 'Fill shells', 'Add toppings'],
    nutrition: { calories: 300, protein: 16, fat: 12, carbs: 32 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: [],
    substitutions: ['Greek yogurt for sour cream'],
  },
  {
    name: 'Quinoa Salad',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Quinoa', 'Cucumber', 'Tomato', 'Feta Cheese', 'Olives', 'Lemon Juice'],
    steps: ['Cook quinoa', 'Mix with veggies and cheese', 'Dress with lemon'],
    nutrition: { calories: 240, protein: 8, fat: 9, carbs: 32 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese'],
  },
  {
    name: 'Chickpea Curry',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Chickpeas', 'Tomato', 'Onion', 'Garlic', 'Spices', 'Coconut Milk'],
    steps: ['Cook onion and garlic', 'Add tomato and spices', 'Add chickpeas and coconut milk'],
    nutrition: { calories: 280, protein: 10, fat: 8, carbs: 40 },
    difficulty: 'Easy',
    cookingTime: 35,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Cream for coconut milk'],
  },
  {
    name: 'Avocado Toast',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Bread', 'Avocado', 'Lemon Juice', 'Salt', 'Pepper'],
    steps: ['Toast bread', 'Mash avocado', 'Spread and season'],
    nutrition: { calories: 220, protein: 5, fat: 12, carbs: 24 },
    difficulty: 'Easy',
    cookingTime: 10,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Gluten-free bread'],
  },
  {
    name: 'Shrimp Pasta',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Pasta', 'Shrimp', 'Garlic', 'Olive Oil', 'Parsley'],
    steps: ['Cook pasta', 'Sauté shrimp and garlic', 'Combine and serve'],
    nutrition: { calories: 410, protein: 22, fat: 14, carbs: 52 },
    difficulty: 'Medium',
    cookingTime: 30,
    dietaryRestrictions: [],
    substitutions: ['Chicken for shrimp'],
  },
  {
    name: 'Spinach Omelette',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Eggs', 'Spinach', 'Cheese', 'Salt', 'Pepper'],
    steps: ['Beat eggs', 'Add spinach and cheese', 'Cook in pan'],
    nutrition: { calories: 180, protein: 12, fat: 10, carbs: 6 },
    difficulty: 'Easy',
    cookingTime: 15,
    dietaryRestrictions: ['Vegetarian'],
    substitutions: ['Vegan cheese'],
  },
  {
    name: 'Stuffed Bell Peppers',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Bell Peppers', 'Rice', 'Ground Beef', 'Tomato Sauce', 'Cheese'],
    steps: ['Prepare peppers', 'Cook filling', 'Stuff and bake'],
    nutrition: { calories: 320, protein: 14, fat: 10, carbs: 42 },
    difficulty: 'Medium',
    cookingTime: 40,
    dietaryRestrictions: [],
    substitutions: ['Ground turkey for beef'],
  },
  {
    name: 'Peanut Butter Cookies',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Peanut Butter', 'Sugar', 'Eggs', 'Baking Soda'],
    steps: ['Mix ingredients', 'Shape cookies', 'Bake'],
    nutrition: { calories: 120, protein: 3, fat: 7, carbs: 12 },
    difficulty: 'Easy',
    cookingTime: 20,
    dietaryRestrictions: ['Gluten-free'],
    substitutions: ['Almond butter'],
  },
  {
    name: 'Vegetable Curry',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Mixed Vegetables', 'Coconut Milk', 'Spices', 'Onion', 'Garlic'],
    steps: ['Cook onion and garlic', 'Add vegetables and spices', 'Add coconut milk and simmer'],
    nutrition: { calories: 260, protein: 7, fat: 10, carbs: 36 },
    difficulty: 'Easy',
    cookingTime: 35,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Cream for coconut milk'],
  },
  {
    name: 'BBQ Chicken Pizza',
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c',
    ingredients: ['Pizza Dough', 'BBQ Sauce', 'Chicken', 'Mozzarella', 'Red Onion', 'Cilantro'],
    steps: ['Prepare dough', 'Add sauce and toppings', 'Bake'],
    nutrition: { calories: 370, protein: 18, fat: 12, carbs: 48 },
    difficulty: 'Medium',
    cookingTime: 40,
    dietaryRestrictions: [],
    substitutions: ['Vegan cheese'],
  },
  {
    name: 'Tofu Stir Fry',
    image: 'https://images.unsplash.com/photo-1464306076886-debede6bbf09',
    ingredients: ['Tofu', 'Broccoli', 'Carrots', 'Soy Sauce', 'Garlic', 'Ginger'],
    steps: ['Chop vegetables', 'Stir fry tofu and veggies', 'Add sauce'],
    nutrition: { calories: 230, protein: 12, fat: 8, carbs: 28 },
    difficulty: 'Easy',
    cookingTime: 25,
    dietaryRestrictions: ['Vegan'],
    substitutions: ['Tamari for soy sauce'],
  },
  {
    name: 'Classic BLT',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ingredients: ['Bread', 'Bacon', 'Lettuce', 'Tomato', 'Mayonnaise'],
    steps: ['Cook bacon', 'Assemble sandwich'],
    nutrition: { calories: 340, protein: 10, fat: 18, carbs: 32 },
    difficulty: 'Easy',
    cookingTime: 15,
    dietaryRestrictions: [],
    substitutions: ['Turkey bacon'],
  },
];

async function seed() {
  await mongoose.connect('mongodb+srv://abhaymulani387:ePh0CM6FWYfrF9J8@smartrecipedb.jetvu49.mongodb.net/?retryWrites=true&w=majority&appName=SmartRecipeDB');
  await Recipe.deleteMany({});
  await Recipe.insertMany(recipes);
  console.log('Seeded 30 recipes');
  mongoose.disconnect();
}

seed();
